; Nyan Cat, AKG format, v1.0.

; Generated by Arkos Tracker 2.

_nyancat_music_Start
_nyancat_music_StartDisarkGenerateExternalLabel

_nyancat_music_DisarkByteRegionStart0
	db "AT20"
_nyancat_music_DisarkPointerRegionStart1
	dw _nyancat_music_ArpeggioTable	; The address of the Arpeggio table.
	dw _nyancat_music_PitchTable	; The address of the Pitch table.
	dw _nyancat_music_InstrumentTable	; The address of the Instrument table.
	dw _nyancat_music_EffectBlockTable	; The address of the Effect Block table.
_nyancat_music_DisarkPointerRegionEnd1


; The addresses of each Subsong:
_nyancat_music_DisarkPointerRegionStart2
	dw _nyancat_music_Subsong0_Start
_nyancat_music_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
_nyancat_music_ArpeggioTable
_nyancat_music_DisarkPointerRegionStart3
_nyancat_music_DisarkPointerRegionEnd3

; Declares all the Pitches.
_nyancat_music_PitchTable
_nyancat_music_DisarkPointerRegionStart4
_nyancat_music_DisarkPointerRegionEnd4

; Declares all the Instruments.
_nyancat_music_InstrumentTable
_nyancat_music_DisarkPointerRegionStart5
	dw _nyancat_music_EmptyInstrument
	dw _nyancat_music_Instrument1
	dw _nyancat_music_Instrument2
	dw _nyancat_music_Instrument3
	dw _nyancat_music_Instrument4
	dw _nyancat_music_Instrument5
_nyancat_music_DisarkPointerRegionEnd5

_nyancat_music_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
_nyancat_music_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

_nyancat_music_Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 241	; Soft only. Volume: 14. Volume only.

	db 121	; Soft only. Volume: 15.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 73	; Soft only. Volume: 9.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 65	; Soft only. Volume: 8.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 57	; Soft only. Volume: 7.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 49	; Soft only. Volume: 6.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 41	; Soft only. Volume: 5.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 33	; Soft only. Volume: 4.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 25	; Soft only. Volume: 3.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 17	; Soft only. Volume: 2.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 9	; Soft only. Volume: 1.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 6	; Loop to silence.

_nyancat_music_Instrument2
	db 1	; The speed (>0, 0 for 256).
_nyancat_music_Instrument2_Loop	db 34	; Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	db 131	; Simple case. Ratio: 4

	db 7	; Loop.
_nyancat_music_DisarkWordForceReference6
	dw _nyancat_music_Instrument2_Loop	; Loop here.

_nyancat_music_Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 1	; Additional data. Noise: 1. Pitch? false. Arp? false. Period? false.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 4	; Arpeggio.

	db 249	; Soft only. Volume: 15. Volume only.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -4	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -8	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -8	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 6	; Loop to silence.

_nyancat_music_Instrument4
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	dw 3549	; Forced period.

	db 241	; Soft only. Volume: 14. Volume only.

	db 232	; No Soft no Hard. Volume: 13. Noise? true.
	db 10	; Noise: 10.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 10	; Noise: 10.

	db 184	; No Soft no Hard. Volume: 7. Noise? true.
	db 10	; Noise: 10.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 10	; Noise: 10.

	db 152	; No Soft no Hard. Volume: 3. Noise? true.
	db 10	; Noise: 10.

	db 144	; No Soft no Hard. Volume: 2. Noise? true.
	db 7	; Noise: 7.

	db 144	; No Soft no Hard. Volume: 2. Noise? true.
	db 4	; Noise: 4.

	db 136	; No Soft no Hard. Volume: 1. Noise? true.
	db 2	; Noise: 2.

	db 136	; No Soft no Hard. Volume: 1. Noise? true.
	db 1	; Noise: 1.

	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

_nyancat_music_Instrument5
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 232	; No Soft no Hard. Volume: 13. Noise? true.
	db 1	; Noise: 1.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
_nyancat_music_EffectBlockTable

_nyancat_music_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
_nyancat_music_Subsong0_DisarkByteRegionStart0
_nyancat_music_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 2	; Loop start index (>=0).
	db 17	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 21	; Base note index (>=0).

_nyancat_music_Subsong0_Linker
_nyancat_music_Subsong0_DisarkPointerRegionStart1
; Position 0
	dw _nyancat_music_Subsong0_Track0
	dw _nyancat_music_Subsong0_Track1
	dw _nyancat_music_Subsong0_Track2
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 1
	dw _nyancat_music_Subsong0_Track3
	dw _nyancat_music_Subsong0_Track1
	dw _nyancat_music_Subsong0_Track4
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 2
_nyancat_music_Subsong0_Linker_Loop
	dw _nyancat_music_Subsong0_Track5
	dw _nyancat_music_Subsong0_Track6
	dw _nyancat_music_Subsong0_Track7
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 3
	dw _nyancat_music_Subsong0_Track8
	dw _nyancat_music_Subsong0_Track9
	dw _nyancat_music_Subsong0_Track10
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 4
	dw _nyancat_music_Subsong0_Track11
	dw _nyancat_music_Subsong0_Track6
	dw _nyancat_music_Subsong0_Track7
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 5
	dw _nyancat_music_Subsong0_Track12
	dw _nyancat_music_Subsong0_Track9
	dw _nyancat_music_Subsong0_Track20
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 6
	dw _nyancat_music_Subsong0_Track5
	dw _nyancat_music_Subsong0_Track6
	dw _nyancat_music_Subsong0_Track7
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 7
	dw _nyancat_music_Subsong0_Track8
	dw _nyancat_music_Subsong0_Track9
	dw _nyancat_music_Subsong0_Track10
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 8
	dw _nyancat_music_Subsong0_Track11
	dw _nyancat_music_Subsong0_Track6
	dw _nyancat_music_Subsong0_Track7
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 9
	dw _nyancat_music_Subsong0_Track13
	dw _nyancat_music_Subsong0_Track9
	dw _nyancat_music_Subsong0_Track19
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 10
	dw _nyancat_music_Subsong0_Track14
	dw _nyancat_music_Subsong0_Track6
	dw _nyancat_music_Subsong0_Track10
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 11
	dw _nyancat_music_Subsong0_Track15
	dw _nyancat_music_Subsong0_Track9
	dw _nyancat_music_Subsong0_Track10
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 12
	dw _nyancat_music_Subsong0_Track16
	dw _nyancat_music_Subsong0_Track6
	dw _nyancat_music_Subsong0_Track10
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 13
	dw _nyancat_music_Subsong0_Track17
	dw _nyancat_music_Subsong0_Track9
	dw _nyancat_music_Subsong0_Track20
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 14
	dw _nyancat_music_Subsong0_Track14
	dw _nyancat_music_Subsong0_Track6
	dw _nyancat_music_Subsong0_Track10
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 15
	dw _nyancat_music_Subsong0_Track15
	dw _nyancat_music_Subsong0_Track9
	dw _nyancat_music_Subsong0_Track10
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 16
	dw _nyancat_music_Subsong0_Track16
	dw _nyancat_music_Subsong0_Track6
	dw _nyancat_music_Subsong0_Track10
	dw _nyancat_music_Subsong0_LinkerBlock0

; Position 17
	dw _nyancat_music_Subsong0_Track18
	dw _nyancat_music_Subsong0_Track9
	dw _nyancat_music_Subsong0_Track19
	dw _nyancat_music_Subsong0_LinkerBlock0

_nyancat_music_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
_nyancat_music_Subsong0_DisarkWordForceReference2
	dw _nyancat_music_Subsong0_Linker_Loop

_nyancat_music_Subsong0_LinkerBlock0
	db 16	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
_nyancat_music_Subsong0_DisarkWordForceReference3
	dw _nyancat_music_Subsong0_SpeedTrack0	; SpeedTrack address.
_nyancat_music_Subsong0_DisarkWordForceReference4
	dw _nyancat_music_Subsong0_EventTrack0	; EventTrack address.

_nyancat_music_Subsong0_Track0
	db 170
	db 1	; New Instrument (1).
	db 43
	db 45
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 42
	db 43
	db 45
	db 50
	db 54
	db 55
	db 54
	db 49
	db 50
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track1
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track2
	db 156
	db 4	; New Instrument (4).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 131
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 156
	db 4	; New Instrument (4).
	db 131
	db 3	; New Instrument (3).
	db 3
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track3
	db 173
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 42
	db 43
	db 45
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 52
	db 49
	db 50
	db 52
	db 55
	db 54
	db 55
	db 54
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track4
	db 131
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 156
	db 4	; New Instrument (4).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 60	; Waits for 1 line.

	db 28
	db 28
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track5
	db 173
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 40
	db 42
	db 60	; Waits for 1 line.

	db 40
	db 41
	db 40
	db 38
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 40
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track6
	db 135
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 18
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 23
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track7
	db 131
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 179
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 156
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 179
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 131
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 179
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 156
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 179
	db 5	; New Instrument (5).
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track8
	db 169
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 41
	db 40
	db 38
	db 40
	db 42
	db 45
	db 47
	db 42
	db 45
	db 40
	db 42
	db 38
	db 40
	db 38
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track9
	db 132
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 16
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 21
	db 60	; Waits for 1 line.

	db 2
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 16
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track10
	db 131
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 179
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 156
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 179
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 131
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 156
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 179
	db 5	; New Instrument (5).
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track11
	db 170
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 42
	db 45
	db 40
	db 42
	db 38
	db 40
	db 42
	db 41
	db 40
	db 38
	db 40
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track12
	db 169
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 38
	db 40
	db 42
	db 45
	db 40
	db 41
	db 40
	db 38
	db 40
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 40
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track13
	db 169
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 38
	db 40
	db 42
	db 45
	db 40
	db 41
	db 40
	db 38
	db 40
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 38
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track14
	db 166
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 33
	db 35
	db 38
	db 60	; Waits for 1 line.

	db 33
	db 35
	db 38
	db 40
	db 42
	db 38
	db 43
	db 42
	db 43
	db 45
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track15
	db 166
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 33
	db 35
	db 38
	db 35
	db 43
	db 42
	db 40
	db 38
	db 31
	db 30
	db 31
	db 33
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track16
	db 166
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 33
	db 35
	db 38
	db 60	; Waits for 1 line.

	db 33
	db 35
	db 38
	db 38
	db 40
	db 42
	db 38
	db 33
	db 35
	db 33
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track17
	db 166
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 38
	db 37
	db 38
	db 33
	db 35
	db 38
	db 43
	db 42
	db 43
	db 45
	db 38
	db 60	; Waits for 1 line.

	db 37
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track18
	db 166
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 38
	db 37
	db 38
	db 33
	db 35
	db 38
	db 43
	db 42
	db 43
	db 45
	db 38
	db 60	; Waits for 1 line.

	db 40
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track19
	db 131
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 179
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 156
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 179
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 131
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 156
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 28
	db 61, 127	; Waits for 128 lines.


_nyancat_music_Subsong0_Track20
	db 131
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 179
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 156
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 179
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 131
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 156
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 28
	db 28
	db 61, 127	; Waits for 128 lines.


; The speed tracks
_nyancat_music_Subsong0_SpeedTrack0
	db 10	; Value: 5.
	db 253	; Wait for 127 lines.

; The event tracks
_nyancat_music_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

_nyancat_music_Subsong0_DisarkByteRegionEnd0
