; doom_e1m1, AKG format, v1.0.

; Generated by Arkos Tracker 2.

doom_e1m1_Start
doom_e1m1_StartDisarkGenerateExternalLabel

doom_e1m1_DisarkByteRegionStart0
	db "AT20"
doom_e1m1_DisarkPointerRegionStart1
	dw doom_e1m1_ArpeggioTable	; The address of the Arpeggio table.
	dw doom_e1m1_PitchTable	; The address of the Pitch table.
	dw doom_e1m1_InstrumentTable	; The address of the Instrument table.
	dw doom_e1m1_EffectBlockTable	; The address of the Effect Block table.
doom_e1m1_DisarkPointerRegionEnd1


; The addresses of each Subsong:
doom_e1m1_DisarkPointerRegionStart2
	dw doom_e1m1_Subsong0_Start
doom_e1m1_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
doom_e1m1_ArpeggioTable
doom_e1m1_DisarkPointerRegionStart3
doom_e1m1_DisarkPointerRegionEnd3

; Declares all the Pitches.
doom_e1m1_PitchTable
doom_e1m1_DisarkPointerRegionStart4
doom_e1m1_DisarkPointerRegionEnd4

; Declares all the Instruments.
doom_e1m1_InstrumentTable
doom_e1m1_DisarkPointerRegionStart5
	dw doom_e1m1_EmptyInstrument
	dw doom_e1m1_Instrument1
	dw doom_e1m1_Instrument2
	dw doom_e1m1_Instrument3
	dw doom_e1m1_Instrument4
	dw doom_e1m1_Instrument5
	dw doom_e1m1_Instrument6
doom_e1m1_DisarkPointerRegionEnd5

doom_e1m1_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
doom_e1m1_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

doom_e1m1_Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 21	; Additional data. Noise: 21. Pitch? false. Arp? false. Period? false.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 4	; Arpeggio.

	db 249	; Soft only. Volume: 15. Volume only.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -4	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -8	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -8	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 6	; Loop to silence.

doom_e1m1_Instrument2
	db 3	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 233	; Soft only. Volume: 13. Volume only.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 217	; Soft only. Volume: 11. Volume only.

	db 81	; Soft only. Volume: 10.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 201	; Soft only. Volume: 9. Volume only.

	db 65	; Soft only. Volume: 8.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 185	; Soft only. Volume: 7. Volume only.

	db 49	; Soft only. Volume: 6.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 169	; Soft only. Volume: 5. Volume only.

	db 33	; Soft only. Volume: 4.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 153	; Soft only. Volume: 3. Volume only.

	db 17	; Soft only. Volume: 2.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 9	; Soft only. Volume: 1.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 6	; Loop to silence.

doom_e1m1_Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 73	; Additional data. Noise: 9. Pitch? false. Arp? true. Period? false.
	db 13	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 9	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 6	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 69	; Additional data. Noise: 5. Pitch? false. Arp? true. Period? false.
	db 4	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 69	; Additional data. Noise: 5. Pitch? false. Arp? true. Period? false.
	db 2	; Arpeggio.

	db 6	; Loop to silence.

doom_e1m1_Instrument4
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 232	; No Soft no Hard. Volume: 13. Noise? true.
	db 1	; Noise: 1.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 200	; No Soft no Hard. Volume: 9. Noise? true.
	db 1	; Noise: 1.

	db 184	; No Soft no Hard. Volume: 7. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 152	; No Soft no Hard. Volume: 3. Noise? true.
	db 1	; Noise: 1.

	db 136	; No Soft no Hard. Volume: 1. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.

doom_e1m1_Instrument5
	db 4	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

doom_e1m1_Instrument5_Loop	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 2	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -2	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 2	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -2	; Pitch.

	db 7	; Loop.
doom_e1m1_DisarkWordForceReference6
	dw doom_e1m1_Instrument5_Loop	; Loop here.

doom_e1m1_Instrument6
	db 3	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 240	; No Soft no Hard. Volume: 14. Noise? true.
	db 1	; Noise: 1.

	db 232	; No Soft no Hard. Volume: 13. Noise? true.
	db 1	; Noise: 1.

	db 224	; No Soft no Hard. Volume: 12. Noise? true.
	db 1	; Noise: 1.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 200	; No Soft no Hard. Volume: 9. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 184	; No Soft no Hard. Volume: 7. Noise? true.
	db 1	; Noise: 1.

	db 176	; No Soft no Hard. Volume: 6. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 160	; No Soft no Hard. Volume: 4. Noise? true.
	db 1	; Noise: 1.

	db 152	; No Soft no Hard. Volume: 3. Noise? true.
	db 1	; Noise: 1.

	db 144	; No Soft no Hard. Volume: 2. Noise? true.
	db 1	; Noise: 1.

	db 136	; No Soft no Hard. Volume: 1. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
doom_e1m1_EffectBlockTable
doom_e1m1_DisarkPointerRegionStart7
	dw doom_e1m1_EffectBlock_P18P240P0	; Index 0
	dw doom_e1m1_EffectBlock_P20P240P0	; Index 1
	dw doom_e1m1_EffectBlock_P4P0	; Index 2
	dw doom_e1m1_EffectBlock_P4P2	; Index 3
	dw doom_e1m1_EffectBlock_P18P32P0	; Index 4
	dw doom_e1m1_EffectBlock_P20P32P0	; Index 5
doom_e1m1_DisarkPointerRegionEnd7

doom_e1m1_EffectBlock_P4P0
	db 4, 0
doom_e1m1_EffectBlock_P4P2
	db 4, 2
doom_e1m1_EffectBlock_P18P32P0
	db 18, 32, 0
doom_e1m1_EffectBlock_P20P32P0
	db 20, 32, 0
doom_e1m1_EffectBlock_P18P240P0
	db 18, 240, 0
doom_e1m1_EffectBlock_P20P240P0
	db 20, 240, 0

doom_e1m1_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
doom_e1m1_Subsong0_DisarkByteRegionStart0
doom_e1m1_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 1	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 1	; Loop start index (>=0).
	db 30	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 28	; Base note index (>=0).

doom_e1m1_Subsong0_Linker
doom_e1m1_Subsong0_DisarkPointerRegionStart1
; Position 0
	dw doom_e1m1_Subsong0_Track24
	dw doom_e1m1_Subsong0_Track24
	dw doom_e1m1_Subsong0_Track24
	dw doom_e1m1_Subsong0_LinkerBlock0

; Position 1
doom_e1m1_Subsong0_Linker_Loop
	dw doom_e1m1_Subsong0_Track1
	dw doom_e1m1_Subsong0_Track0
	dw doom_e1m1_Subsong0_Track2
	dw doom_e1m1_Subsong0_LinkerBlock1

; Position 2
	dw doom_e1m1_Subsong0_Track1
	dw doom_e1m1_Subsong0_Track0
	dw doom_e1m1_Subsong0_Track2
	dw doom_e1m1_Subsong0_LinkerBlock1

; Position 3
	dw doom_e1m1_Subsong0_Track3
	dw doom_e1m1_Subsong0_Track0
	dw doom_e1m1_Subsong0_Track4
	dw doom_e1m1_Subsong0_LinkerBlock1

; Position 4
	dw doom_e1m1_Subsong0_Track3
	dw doom_e1m1_Subsong0_Track0
	dw doom_e1m1_Subsong0_Track5
	dw doom_e1m1_Subsong0_LinkerBlock2

; Position 5
	dw doom_e1m1_Subsong0_Track24
	dw doom_e1m1_Subsong0_Track6
	dw doom_e1m1_Subsong0_Track7
	dw doom_e1m1_Subsong0_LinkerBlock3

; Position 6
	dw doom_e1m1_Subsong0_Track8
	dw doom_e1m1_Subsong0_Track0
	dw doom_e1m1_Subsong0_Track9
	dw doom_e1m1_Subsong0_LinkerBlock1

; Position 7
	dw doom_e1m1_Subsong0_Track8
	dw doom_e1m1_Subsong0_Track0
	dw doom_e1m1_Subsong0_Track9
	dw doom_e1m1_Subsong0_LinkerBlock2

; Position 8
	dw doom_e1m1_Subsong0_Track16
	dw doom_e1m1_Subsong0_Track10
	dw doom_e1m1_Subsong0_Track11
	dw doom_e1m1_Subsong0_LinkerBlock3

; Position 9
	dw doom_e1m1_Subsong0_Track12
	dw doom_e1m1_Subsong0_Track13
	dw doom_e1m1_Subsong0_Track9
	dw doom_e1m1_Subsong0_LinkerBlock1

; Position 10
	dw doom_e1m1_Subsong0_Track12
	dw doom_e1m1_Subsong0_Track13
	dw doom_e1m1_Subsong0_Track9
	dw doom_e1m1_Subsong0_LinkerBlock2

; Position 11
	dw doom_e1m1_Subsong0_Track14
	dw doom_e1m1_Subsong0_Track15
	dw doom_e1m1_Subsong0_Track11
	dw doom_e1m1_Subsong0_LinkerBlock3

; Position 12
	dw doom_e1m1_Subsong0_Track8
	dw doom_e1m1_Subsong0_Track0
	dw doom_e1m1_Subsong0_Track9
	dw doom_e1m1_Subsong0_LinkerBlock1

; Position 13
	dw doom_e1m1_Subsong0_Track16
	dw doom_e1m1_Subsong0_Track17
	dw doom_e1m1_Subsong0_Track18
	dw doom_e1m1_Subsong0_LinkerBlock4

; Position 14
	dw doom_e1m1_Subsong0_Track19
	dw doom_e1m1_Subsong0_Track20
	dw doom_e1m1_Subsong0_Track21
	dw doom_e1m1_Subsong0_LinkerBlock1

; Position 15
	dw doom_e1m1_Subsong0_Track8
	dw doom_e1m1_Subsong0_Track0
	dw doom_e1m1_Subsong0_Track9
	dw doom_e1m1_Subsong0_LinkerBlock2

; Position 16
	dw doom_e1m1_Subsong0_Track1
	dw doom_e1m1_Subsong0_Track22
	dw doom_e1m1_Subsong0_Track23
	dw doom_e1m1_Subsong0_LinkerBlock3

; Position 17
	dw doom_e1m1_Subsong0_Track1
	dw doom_e1m1_Subsong0_Track0
	dw doom_e1m1_Subsong0_Track2
	dw doom_e1m1_Subsong0_LinkerBlock1

; Position 18
	dw doom_e1m1_Subsong0_Track1
	dw doom_e1m1_Subsong0_Track0
	dw doom_e1m1_Subsong0_Track2
	dw doom_e1m1_Subsong0_LinkerBlock2

; Position 19
	dw doom_e1m1_Subsong0_Track24
	dw doom_e1m1_Subsong0_Track25
	dw doom_e1m1_Subsong0_Track26
	dw doom_e1m1_Subsong0_LinkerBlock3

; Position 20
	dw doom_e1m1_Subsong0_Track27
	dw doom_e1m1_Subsong0_Track0
	dw doom_e1m1_Subsong0_Track9
	dw doom_e1m1_Subsong0_LinkerBlock1

; Position 21
	dw doom_e1m1_Subsong0_Track27
	dw doom_e1m1_Subsong0_Track0
	dw doom_e1m1_Subsong0_Track9
	dw doom_e1m1_Subsong0_LinkerBlock2

; Position 22
	dw doom_e1m1_Subsong0_Track16
	dw doom_e1m1_Subsong0_Track28
	dw doom_e1m1_Subsong0_Track29
	dw doom_e1m1_Subsong0_LinkerBlock3

; Position 23
	dw doom_e1m1_Subsong0_Track30
	dw doom_e1m1_Subsong0_Track13
	dw doom_e1m1_Subsong0_Track9
	dw doom_e1m1_Subsong0_LinkerBlock1

; Position 24
	dw doom_e1m1_Subsong0_Track30
	dw doom_e1m1_Subsong0_Track13
	dw doom_e1m1_Subsong0_Track9
	dw doom_e1m1_Subsong0_LinkerBlock2

; Position 25
	dw doom_e1m1_Subsong0_Track14
	dw doom_e1m1_Subsong0_Track31
	dw doom_e1m1_Subsong0_Track32
	dw doom_e1m1_Subsong0_LinkerBlock3

; Position 26
	dw doom_e1m1_Subsong0_Track27
	dw doom_e1m1_Subsong0_Track0
	dw doom_e1m1_Subsong0_Track9
	dw doom_e1m1_Subsong0_LinkerBlock1

; Position 27
	dw doom_e1m1_Subsong0_Track35
	dw doom_e1m1_Subsong0_Track17
	dw doom_e1m1_Subsong0_Track18
	dw doom_e1m1_Subsong0_LinkerBlock4

; Position 28
	dw doom_e1m1_Subsong0_Track33
	dw doom_e1m1_Subsong0_Track20
	dw doom_e1m1_Subsong0_Track9
	dw doom_e1m1_Subsong0_LinkerBlock1

; Position 29
	dw doom_e1m1_Subsong0_Track27
	dw doom_e1m1_Subsong0_Track0
	dw doom_e1m1_Subsong0_Track9
	dw doom_e1m1_Subsong0_LinkerBlock2

; Position 30
	dw doom_e1m1_Subsong0_Track1
	dw doom_e1m1_Subsong0_Track34
	dw doom_e1m1_Subsong0_Track5
	dw doom_e1m1_Subsong0_LinkerBlock3

doom_e1m1_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
doom_e1m1_Subsong0_DisarkWordForceReference2
	dw doom_e1m1_Subsong0_Linker_Loop

doom_e1m1_Subsong0_LinkerBlock0
	db 8	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
doom_e1m1_Subsong0_DisarkWordForceReference3
	dw doom_e1m1_Subsong0_SpeedTrack0	; SpeedTrack address.
doom_e1m1_Subsong0_DisarkWordForceReference4
	dw doom_e1m1_Subsong0_EventTrack0	; EventTrack address.
doom_e1m1_Subsong0_LinkerBlock1
	db 32	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
doom_e1m1_Subsong0_DisarkWordForceReference5
	dw doom_e1m1_Subsong0_SpeedTrack0	; SpeedTrack address.
doom_e1m1_Subsong0_DisarkWordForceReference6
	dw doom_e1m1_Subsong0_EventTrack0	; EventTrack address.
doom_e1m1_Subsong0_LinkerBlock2
	db 24	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
doom_e1m1_Subsong0_DisarkWordForceReference7
	dw doom_e1m1_Subsong0_SpeedTrack0	; SpeedTrack address.
doom_e1m1_Subsong0_DisarkWordForceReference8
	dw doom_e1m1_Subsong0_EventTrack0	; EventTrack address.
doom_e1m1_Subsong0_LinkerBlock3
	db 16	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
doom_e1m1_Subsong0_DisarkWordForceReference9
	dw doom_e1m1_Subsong0_SpeedTrack1	; SpeedTrack address.
doom_e1m1_Subsong0_DisarkWordForceReference10
	dw doom_e1m1_Subsong0_EventTrack0	; EventTrack address.
doom_e1m1_Subsong0_LinkerBlock4
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
doom_e1m1_Subsong0_DisarkWordForceReference11
	dw doom_e1m1_Subsong0_SpeedTrack1	; SpeedTrack address.
doom_e1m1_Subsong0_DisarkWordForceReference12
	dw doom_e1m1_Subsong0_EventTrack0	; EventTrack address.

doom_e1m1_Subsong0_Track0
	db 204
	db 5	; New Instrument (5).
	db 2	; Index to an effect block.
	db 12
	db 24
	db 12
	db 12
	db 22
	db 12
	db 12
	db 20
	db 12
	db 12
	db 18
	db 12
	db 12
	db 19
	db 20
	db 12
	db 12
	db 24
	db 12
	db 12
	db 22
	db 12
	db 12
	db 20
	db 12
	db 12
	db 18
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track1
	db 192
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 61, 14	; Waits for 15 lines.

	db 0
	db 61, 9	; Waits for 10 lines.

	db 140
	db 5	; New Instrument (5).
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track2
	db 128
	db 1	; New Instrument (1).
	db 61, 14	; Waits for 15 lines.

	db 0
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track3
	db 192
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 0
	db 12
	db 0
	db 0
	db 10
	db 0
	db 0
	db 8
	db 0
	db 0
	db 6
	db 0
	db 0
	db 7
	db 8
	db 0
	db 0
	db 12
	db 0
	db 0
	db 10
	db 0
	db 0
	db 8
	db 0
	db 0
	db 204
	db 5	; New Instrument (5).
	db 2	; Index to an effect block.
	db 124	; No note, but effects.
	db 5	; Index to an effect block.
	db 124	; No note, but effects.
	db 4	; Index to an effect block.
	db 124	; No note, but effects.
	db 5	; Index to an effect block.
	db 124	; No note, but effects.
	db 4	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track4
	db 128
	db 1	; New Instrument (1).
	db 61, 14	; Waits for 15 lines.

	db 0
	db 61, 12	; Waits for 13 lines.

	db 152
	db 4	; New Instrument (4).
	db 24
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track5
	db 128
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 148
	db 6	; New Instrument (6).
	db 61, 6	; Waits for 7 lines.

	db 128
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track6
	db 230
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 36
	db 35
	db 38
	db 41
	db 39
	db 38
	db 35
	db 38
	db 39
	db 41
	db 43
	db 41
	db 39
	db 38
	db 35
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track7
	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track8
	db 192
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 0
	db 140
	db 5	; New Instrument (5).
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track9
	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 0
	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 0
	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 0
	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 0
	db 140
	db 3	; New Instrument (3).
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track10
	db 235
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 39
	db 36
	db 39
	db 43
	db 39
	db 43
	db 48
	db 43
	db 39
	db 43
	db 39
	db 43
	db 48
	db 51
	db 55
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track11
	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 12
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track12
	db 197
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 145
	db 5	; New Instrument (5).
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track13
	db 209
	db 5	; New Instrument (5).
	db 2	; Index to an effect block.
	db 17
	db 29
	db 17
	db 17
	db 27
	db 17
	db 17
	db 25
	db 17
	db 17
	db 23
	db 17
	db 17
	db 24
	db 25
	db 17
	db 17
	db 29
	db 17
	db 17
	db 27
	db 17
	db 17
	db 153
	db 2	; New Instrument (2).
	db 145
	db 5	; New Instrument (5).
	db 17
	db 23
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track14
	db 197
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 5
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track15
	db 233
	db 5	; New Instrument (5).
	db 3	; Index to an effect block.
	db 166
	db 2	; New Instrument (2).
	db 36
	db 41
	db 36
	db 32
	db 36
	db 41
	db 44
	db 41
	db 36
	db 41
	db 36
	db 41
	db 36
	db 32
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track16
	db 192
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 60	; Waits for 1 line.

	db 140
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track17
	db 204
	db 5	; New Instrument (5).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 18
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 19
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 22
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 18
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track18
	db 128
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 140
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 128
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 140
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 128
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 140
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 128
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 140
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 0
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 12
	db 128
	db 1	; New Instrument (1).
	db 0
	db 140
	db 3	; New Instrument (3).
	db 12
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 12
	db 128
	db 1	; New Instrument (1).
	db 0
	db 140
	db 3	; New Instrument (3).
	db 12
	db 128
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track19
	db 201
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 5
	db 60	; Waits for 1 line.

	db 5
	db 145
	db 5	; New Instrument (5).
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track20
	db 213
	db 5	; New Instrument (5).
	db 2	; Index to an effect block.
	db 21
	db 33
	db 21
	db 21
	db 31
	db 21
	db 21
	db 29
	db 21
	db 21
	db 27
	db 21
	db 21
	db 28
	db 29
	db 19
	db 19
	db 31
	db 19
	db 19
	db 29
	db 19
	db 19
	db 27
	db 18
	db 17
	db 25
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track21
	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 0
	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 0
	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 0
	db 140
	db 3	; New Instrument (3).
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track22
	db 231
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 43
	db 36
	db 31
	db 39
	db 36
	db 43
	db 39
	db 43
	db 39
	db 36
	db 31
	db 39
	db 43
	db 48
	db 51
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track23
	db 128
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 164
	db 6	; New Instrument (6).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 164
	db 4	; New Instrument (4).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 164
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 36
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track24
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track25
	db 230
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 36
	db 35
	db 31
	db 41
	db 38
	db 35
	db 31
	db 43
	db 41
	db 38
	db 35
	db 47
	db 45
	db 43
	db 41
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track26
	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 60	; Waits for 1 line.

	db 12
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track27
	db 192
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 155
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 128
	db 2	; New Instrument (2).
	db 154
	db 5	; New Instrument (5).
	db 128
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 151
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 128
	db 2	; New Instrument (2).
	db 150
	db 5	; New Instrument (5).
	db 128
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 150
	db 5	; New Instrument (5).
	db 24
	db 128
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 155
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 128
	db 2	; New Instrument (2).
	db 154
	db 5	; New Instrument (5).
	db 128
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 152
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 128
	db 2	; New Instrument (2).
	db 149
	db 5	; New Instrument (5).
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track28
	db 243
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 48
	db 43
	db 39
	db 48
	db 51
	db 48
	db 43
	db 39
	db 43
	db 48
	db 43
	db 51
	db 48
	db 43
	db 39
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track29
	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track30
	db 197
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 160
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 133
	db 2	; New Instrument (2).
	db 159
	db 5	; New Instrument (5).
	db 133
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 156
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 133
	db 2	; New Instrument (2).
	db 155
	db 5	; New Instrument (5).
	db 133
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 155
	db 5	; New Instrument (5).
	db 29
	db 133
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 160
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 133
	db 2	; New Instrument (2).
	db 159
	db 5	; New Instrument (5).
	db 133
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 157
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 133
	db 2	; New Instrument (2).
	db 155
	db 5	; New Instrument (5).
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track31
	db 233
	db 5	; New Instrument (5).
	db 3	; Index to an effect block.
	db 37
	db 36
	db 41
	db 36
	db 32
	db 36
	db 41
	db 44
	db 41
	db 36
	db 41
	db 36
	db 41
	db 36
	db 32
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track32
	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 0
	db 140
	db 3	; New Instrument (3).
	db 12
	db 128
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 140
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 128
	db 1	; New Instrument (1).
	db 0
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track33
	db 201
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 167
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 137
	db 2	; New Instrument (2).
	db 166
	db 5	; New Instrument (5).
	db 137
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 164
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 137
	db 2	; New Instrument (2).
	db 161
	db 5	; New Instrument (5).
	db 137
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 5	; New Instrument (5).
	db 36
	db 135
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 166
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 135
	db 2	; New Instrument (2).
	db 164
	db 5	; New Instrument (5).
	db 135
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 163
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 133
	db 2	; New Instrument (2).
	db 159
	db 5	; New Instrument (5).
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track34
	db 235
	db 2	; New Instrument (2).
	db 3	; Index to an effect block.
	db 41
	db 38
	db 35
	db 31
	db 29
	db 26
	db 23
	db 47
	db 45
	db 43
	db 41
	db 38
	db 35
	db 31
	db 29
	db 61, 127	; Waits for 128 lines.


doom_e1m1_Subsong0_Track35
	db 192
	db 2	; New Instrument (2).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 155
	db 5	; New Instrument (5).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 128
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 154
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 128
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 151
	db 5	; New Instrument (5).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 128
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 150
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 128
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 150
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 24
	db 60	; Waits for 1 line.

	db 128
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 155
	db 5	; New Instrument (5).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 128
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 154
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 128
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 152
	db 5	; New Instrument (5).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 128
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 149
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


; The speed tracks
doom_e1m1_Subsong0_SpeedTrack0
	db 12	; Value: 6.
	db 253	; Wait for 127 lines.
doom_e1m1_Subsong0_SpeedTrack1
	db 6	; Value: 3.
	db 253	; Wait for 127 lines.

; The event tracks
doom_e1m1_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

doom_e1m1_Subsong0_DisarkByteRegionEnd0
